source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0.4"
# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "kamal", require: false

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem "thruster", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem "rack-cors"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false

  # [https://github.com/thoughtbot/factory_bot_rails]
  gem 'factory_bot_rails', '~> 6.5.1'
  
  # Generate fake data such as names, addresses, and phone numbers [https://github.com/faker-ruby/faker]
  gem 'faker', '~> 3.5.2'

  # RSpec test gem used with Rails [https://github.com/rspec/rspec-rails]
  gem 'rspec-rails', '~> 8.0.2'

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false

  # Performance optimization analysis for your projects, as an extension to RuboCop [https://github.com/rubocop/rubocop-performance]
  gem 'rubocop-performance', '~> 1.26.1', require: false
  
  # Analysis rails code, as an extension to RuboCop [https://github.com/rubocop/rubocop-rails]
  gem 'rubocop-rails', '~> 2.33.4', require: false
end

group :test do
  # ActiveRecord integration with Database Cleaner gem (https://github.com/DatabaseCleaner/database_cleaner).
  gem 'database_cleaner-active_record', '~> 2.2.2'
  
  # Rubocop extension for FactoryBot [https://github.com/rubocop/rubocop-factory_bot]
  gem 'rubocop-factory_bot', '~> 2.27.1', require: false
  
  # Rubocop extension for Rspec [https://github.com/rubocop/rubocop-rspec]
  gem 'rubocop-rspec', '~> 3.7.0', require: false

  # RSpec one-liners to test common Rails functionality [https://github.com/thoughtbot/shoulda-matchers]
  gem 'shoulda-matchers', '~> 6.5.0'
end
